name: Generate Release Notes

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './kube-app'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get commit history
        id: commits
        run: |
          git fetch origin main
          COMMITS=$(git log origin/main..HEAD --pretty=format:"- %s (%an)")
          # This should also be a single line to avoid issues.
          echo "COMMITS=$COMMITS" >> $GITHUB_ENV

      # Save multiline PR body into an environment variable safely
      - name: Save PR body to env
        run: |
          cat <<'EOF' >> $GITHUB_ENV
          PR_BODY<<EOT
          ${{ github.event.pull_request.body }}
          EOT
          EOF

      - name: Generate CHANGELOG.md from PR body
        env:
          COMMITS: ${{ env.COMMITS }}   # keep if you already set COMMITS earlier
        run: |
          {
            echo "# Changelog"
            echo
            echo "### Description"
            # Use quoted variable expansion to preserve content exactly
            printf '%s\n' "$PR_BODY"
            echo
            echo "### Commits"
            printf '%s\n' "$COMMITS"
          } > CHANGELOG.md

      - name: Show generated file (debug)
        run: |
          echo "Current directory:"
          pwd
          cat CHANGELOG.md

      - name: Commit and push CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update CHANGELOG.md for PR #${{ github.event.pull_request.number }}"
          file_pattern: '*CHANGELOG.md'