name: Generate Release Notes

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './kube-app'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get commit history
        id: commits
        run: |
          git fetch origin main
          COMMITS=$(git log origin/main..HEAD --pretty=format:"- %s (%an)")
          # This should also be a single line to avoid issues.
          echo "COMMITS=$COMMITS" >> $GITHUB_ENV

      - name: Generate CHANGELOG.md
        run: |
          echo "# Changelog" > CHANGELOG.md
          echo "### Description" >> CHANGELOG.md
          echo "PR_DESCRIPTION=${{ github.event.pull_request.body }}" >> CHANGELOG.md
          echo "### Commits" >> CHANGELOG.md
          echo "${{ env.COMMITS }}" >> CHANGELOG.md

      - name: Commit and push CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update CHANGELOG.md for PR #${{ github.event.pull_request.number }}"
          file_pattern: CHANGELOG.md