name: Update Helm Docs and Release Notes

on:
  pull_request_review:
    types: [submitted]

jobs:
  update-docs:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './kube-app'
    steps:

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      # README Generation Steps
      - name: Generate Helm Docs README.md
        run: |
          docker run --rm -v ${{ github.workspace }}:/helm-docs jnorwood/helm-docs:latest

      # Release Notes Generation Steps
      - name: Save PR body to env
        run: |
          cat <<'EOF' >> $GITHUB_ENV
          PR_BODY<<EOT
          ${{ github.event.pull_request.body }}
          EOT
          EOF

      - name: Generate Release Notes CHANGELOG.md from PR body
        run: |
          {
            echo "# Changelog"
            echo
            echo "### Description"
            # Use quoted variable expansion to preserve content exactly
            printf '%s\n' "$PR_BODY"
          } > CHANGELOG.md

      # Commit Changes
      - name: Commit updated README.md and CHANGELOG.md to PR
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md CHANGELOG.md
          git commit -m "docs: update README.md and CHANGELOG.md"
          git push origin HEAD:${{ github.event.pull_request.head.ref }}