name: Update Helm Docs

on:
  pull_request:
    types: [synchronize, opened]

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Save current README.md
        run: cp README.md README.md.old

      - name: Run helm-docs Docker image
        run: |
          docker run --rm -v ${{ github.workspace }}:/helm-docs jnorwood/helm-docs:latest

      - name: Compare README.md files
        id: readme_diff
        run: |
          if cmp -s README.md README.md.old; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Check last commit author and message
        id: last_commit
        run: |
          AUTHOR=$(git log -1 --pretty=format:'%an')
          MESSAGE=$(git log -1 --pretty=format:'%s')
          if [[ "$AUTHOR" == "github-actions[bot]" && "$MESSAGE" == "docs: update README.md with helm-docs" ]]; then
            echo "skip_commit=true" >> $GITHUB_OUTPUT
          else
            echo "skip_commit=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit updated README.md to PR
        if: steps.readme_diff.outputs.changed == 'true' && steps.last_commit.outputs.skip_commit == 'false'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: update README.md with helm-docs"
          git push origin HEAD:${{ github.head_ref }}