name: Validate Helm Docs and Release Notes Generation

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  validate-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './kube-app'
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      # README Generation Validation
      - name: Validate Helm Docs README.md generation
        run: |
          docker run --rm -v ${{ github.workspace }}:/helm-docs jnorwood/helm-docs:latest
          # Check if README.md was generated
          test -f README.md

      # Release Notes Generation Validation
      - name: Save PR body to env
        run: |
          cat <<'EOF' >> $GITHUB_ENV
          PR_BODY<<EOT
          ${{ github.event.pull_request.body }}
          EOT
          EOF

      - name: Validate Release Notes CHANGELOG.md generation from PR body
        run: |
          {
            echo "# Changelog"
            echo
            echo "### Description"
            printf '%s\n' "$PR_BODY"
          } > CHANGELOG.md
          # Check if CHANGELOG.md was generated
          test -f CHANGELOG.md

      - name: Display generated CHANGELOG.md
        run: cat CHANGELOG.md

      - name: Display generated README.md
        run: cat README.md

      - name: Check if README.md and CHANGELOG.md are not empty
        run: |
          if [ ! -s README.md ]; then
            echo "README.md is empty"
            exit 1
          fi
          if [ ! -s CHANGELOG.md ]; then
            echo "CHANGELOG.md is empty"
            exit 1
          fi